package com.poudel.taskmaster.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Date;


@DynamoDBTable(tableName = "task")
public class History {
    private String id;
    private Date date;
    private String action;

    public History(){}

    public History(Date date, String action) {
        this.date = date;
        this.action = action;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
    @DynamoDBAttribute
    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }
}
