package com.poudel.taskmaster.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Date;

@DynamoDBDocument
public class History {
    //private String id;
    private String date;
    private String action;

    public History(){}

    public History(Date date, String action) {
        this.date = date.toString();
        this.action = action;
    }

    //@DynamoDBHashKey
    //@DynamoDBAutoGeneratedKey
    //public String getId() {
   //     return id;
   // }

    //public void setId(String id) {
    //    this.id = id;
    //}

    @DynamoDBAttribute
    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }
    @DynamoDBAttribute
    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }
}
